wip feat/deploy-job

diff --git a/templates/deployment/Jenkinsfile b/templates/deployment/Jenkinsfile
--- a/templates/deployment/Jenkinsfile
+++ b/templates/deployment/Jenkinsfile
@@ -61,6 +61,11 @@ pipeline {
               kustomize edit set image ${params.target_service}=${fullImage}
               if [[ ${params.enable_job_deployment} == true ]]; then
                 sed -i "s/value: ${params.target_service}-.*\$/value: ${params.target_service}-${params.tag}/" "kustomization.yaml"
+                if [[ \$? -ne "0" ]]; then
+                  echo "[WARN] Error updating ${params.target_service} job name with ${params.tag}, it does not exist."
+                  exit 1
+                fi
+                  echo "[LOG] Updated ${params.target_service} job name with ${params.tag}"
               fi
               git config --global --add safe.directory "${WORKSPACE}"
               git config --global user.email '${params.git_author_email}'
